# ----------------------------------------------
# Установка Docker на все ноды
# ----------------------------------------------
- name: Preconfig
  hosts: swarm
  become: true
  tasks:
    - name: Docker installation
      block:
      - name: "Step 1: Update cache and install prerequisite packages"
        apt:
          name:
            - ca-certificates
            - curl
          state: present
          update_cache: yes

      - name: "Steps 2: Add Docker repository using deb822"
        ansible.builtin.deb822_repository:
          name: docker
          types: deb
          uris: https://download.docker.com/linux/ubuntu
          suites: "{{ ansible_facts['distribution_release'] }}"
          components: stable
          architectures: amd64
          signed_by: https://download.docker.com/linux/ubuntu/gpg
          state: present
          install_python_debian: true

      - name: "Step 3: Install Docker"
        apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          state: present
          update_cache: yes

      - name: "Step 4: Ensure Docker is started and enabled"
        service:
          name: docker
          state: started
          enabled: yes

      - name: "Step 5: Add Docker to user groups"
        user:
          name: "{{ ansible_user }}"
          groups: docker
          append: true

      - name: "Step 6: Reboot the server"
        reboot:

# ----------------------------------------------
# Инициализация Swarm на первой ноде (server-1)
# ----------------------------------------------
- name: Initialize Docker Swarm Leader
  hosts: swarm_managers[0]
  become: true
  tasks:
    - name: Check if Swarm is already initialized
      command: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
      register: swarm_status
      changed_when: false

    - name: Initialize Swarm Cluster
      command: >
        docker swarm init 
        --advertise-addr {{ cluster_ip }}
      when: swarm_status.stdout == "inactive"

    - name: Get Manager Join Token
      command: docker swarm join-token -q manager
      register: manager_token
      changed_when: false

    - name: Get Worker Join Token
      command: docker swarm join-token -q worker
      register: worker_token
      changed_when: false

# ----------------------------------------------
# Подключение дополнительных Менеджеров (server-2, server-3)
# ----------------------------------------------
- name: Join Remaining Managers to Swarm
  hosts: swarm_managers[1:]
  become: true
  tasks:
    - name: Check if already in Swarm
      command: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
      register: swarm_status
      changed_when: false

    - name: Join as Manager
      command: >
        docker swarm join 
        --token {{ hostvars[groups['swarm_managers'][0]]['manager_token']['stdout'] }} 
        {{ hostvars[groups['swarm_managers'][0]]['cluster_ip'] }}:2377
      when: swarm_status.stdout == "inactive"

# ----------------------------------------------
# Подключение Воркеров (server-4, server-5)
# ----------------------------------------------
- name: Join Workers to Swarm
  hosts: swarm_workers
  become: true
  tasks:
    - name: Check if already in Swarm
      command: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
      register: swarm_status
      changed_when: false

    - name: Join as Worker
      command: >
        docker swarm join 
        --token {{ hostvars[groups['swarm_managers'][0]]['worker_token']['stdout'] }} 
        {{ hostvars[groups['swarm_managers'][0]]['cluster_ip'] }}:2377
      when: swarm_status.stdout == "inactive"
